AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chinook Entity Server Lambda

Resources:
  ChinookEntityServer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../build/libs/chinook-lambda.jar
      Handler: is.codion.framework.lambda.LambdaEntityHandler::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-Dcodion.db.url=jdbc:h2:mem:h2db -Dcodion.db.initScripts=classpath:create_schema.sql -Dcodion.db.countQueries=true -Dcodion.server.connectionPoolUsers=scott:tiger -Dcodion.server.objectInputFilterFactoryClassName=is.codion.common.rmi.server.SerializationFilterFactory -Dcodion.server.serialization.filter.patternFile=classpath:serialization-filter-patterns.txt -Dcodion.server.idleConnectionTimeout=600000"
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
            - OPTIONS
          AllowHeaders:
            - "*"
          ExposeHeaders:
            - "*"
          MaxAge: 3600

Outputs:
  EntityServerFunctionUrl:
    Description: "Lambda Function URL endpoint"
    Value: !GetAtt ChinookEntityServer.FunctionUrl